### ISSUE TITLE
Driver is being registered twice

### ISSUE THREAD

**Issue by knowmercy** [lib/pq#238]
I recently replaced bmizerany/pq with lib/pq and despite having no references left to bmizerany/pq in my code I'm getting an error at runtime. This is on a -tip build of Go.

panic: sql: Register called twice for driver postgres

goroutine 16 [running]:
runtime.panic(0x6f6420, 0xc2080009a0)
        /home/bmercer/go/src/pkg/runtime/panic.c:250 +0xb4
database/sql.Register(0x831fd0, 0x8, 0x7f68a5408680, 0xcbcf68)
        /home/bmercer/go/src/pkg/database/sql/sql.go:35 +0x125
github.com/lib/pq.init·1()
        /home/bmercer/gopath/src/github.com/lib/pq/conn.go:37 +0x7e
github.com/lib/pq.init()
        ?:0 +0x38b
main.init()
        /home/bmercer/edigate-go/handlers.go:527 +0x72
exit status 2

**Comment by ezbercih** [comment]
We are having the same problem. I am not sure how the package's init is guaranteed to run once if the package is imported twice. To get around this, I added sync.Once trick as below and it seems to work fine:
```
var once sync.Once

func init() {
	once.Do(sql.Register("postgres", &drv{}))
}
```

Should this be a pull request, is there a better way to solve this or is this not even a problem? What we are experiencing suggests otherwise.

**Comment by jmscott** [comment]
On Fri, Dec 18, 2015 at 1:49 PM, Cem Ezberci <notifications@github.com>
wrote:

> We are having the same problem. I am not sure how the package's init is
> guaranteed to run once if the package is imported twice. To get around
> this, I added sync.Once trick as below and it seems to work fine:
>
> var once sync.Once
>
> func init() {
>     once.Do(sql.Register("postgres", &drv{}))
> }
>
> isn't an init{} already guaranteed by golang runtime to run only once?

    https://golang.org/ref/spec#Package_initialization

-j

>

**Comment by dankinder** [comment]
I ran into this and figured out what was going on; for the sake of future google searchers here is what might be happing if you see this error.

I was in a project with vendored dependencies, so 2 version of lib/pq existed: one in my project's `vendor/` directory and another in `$GOPATH/src/github.com/lib/pq`. Normally this wouldn't be an issue, since the project should use the vendored one. But I failed to vendor a third dependency (in this case mattest/migrate), so it was getting built out of my GOPATH, and that imports lib/pq so used the GOPATH version of lib/pq for that. So two lib/pq packages would get built, both have their init() called... 💥

**Comment by CryLittleSister** [comment]
> I ran into this and figured out what was going on; for the sake of future google searchers here is what might be happing if you see this error.
> 
> I was in a project with vendored dependencies, so 2 version of lib/pq existed: one in my project's `vendor/` directory and another in `$GOPATH/src/github.com/lib/pq`. Normally this wouldn't be an issue, since the project should use the vendored one. But I failed to vendor a third dependency (in this case mattest/migrate), so it was getting built out of my GOPATH, and that imports lib/pq so used the GOPATH version of lib/pq for that. So two lib/pq packages would get built, both have their init() called... 💥

What is the solution to this?

**Comment by dankinder** [comment]
@CryLittleSister the solution is to make sure you have all of your dependencies vendored (or none of them). How to do this will depend on what dependency manager you're using.
