### ISSUE TITLE
Support to Text(Un)Marshaler

### ISSUE THREAD

**Issue by rafaeljusto** [lib/pq#339]
It would be great if we could use the TextMarsheler and TextUnmarshaler interfaces to automatically convert our custom types to or from an array of bytes and persist it into the postgresql database. This would make the library more flexible.

This interface were introduced in Go 1.2 and are described here:
http://golang.org/pkg/encoding/

**Comment by johto** [comment]
The database/sql library is using the [driver.Valuer](http://golang.org/pkg/database/sql/driver/#Valuer) and [sql.Scanner](http://golang.org/pkg/database/sql/#Scanner) interfaces for this, and the drivers can't really do anything about that since they never see the original value.  Did you find those interfaces unsatisfactory in some way?

**Comment by rafaeljusto** [comment]
My bad! The interfaces driver.Valuer and sql.Scanner are exactly what I was looking for. Thanks!
