### ISSUE TITLE
Option to have rows.Next() return a byte array

### ISSUE THREAD

**Issue by pkieltyka** [lib/pq#345]
I have been working with `pq` through the https://github.com/upper/db lightweight data mapper. I'm quite fond of upper's abstraction for querying, however, it has required a fork of `pq` that patches the `rows.Next()` method thats returns the raw byte array of the row instead of calling `decode()` and returning a particular type in pq. See: https://github.com/pkieltyka/pq/commit/47509abd04b2ecbda716cfa31bce26aacec0b6d2

With a byte array, the caller can use sql.RawBytes and sql.Scan() to translate the data, which is what I need to do.

I'd like to submit a patch that adds a variable on the `rows` struct like `decode bool` that will change the behavior of Next() to use pq's decode() method, or leave it up to the caller. It would also require a configuration variable somewhere to instruct the pq to work in this mode.

similarly, the main golang mysql driver offers a `binaryRows` that returns byte arrays and uses `sql.Scan()` to decode the data. See: https://github.com/go-sql-driver/mysql/blob/master/rows.go#L68-L78

please let me know if there is interest in this and I am happy to submit a patch, or maybe someone has a suggestion for a better approach. Thanks.

**Comment by cbandy** [comment]
Which Postgres types are causing you trouble, exactly?

**Comment by cbandy** [comment]
I've read some of the code you linked and it seems the authors misunderstand how `Scan` works.

A `Driver` [returns a `Value`](http://golang.org/pkg/database/sql/driver/#Rows) to the `sql` package which, in turn, converts the `Value` to the scan destination. `RawBytes` only works when the `sql` package can [convert the `Value` to `[]byte`](https://github.com/golang/go/blob/go1.1/src/pkg/database/sql/convert.go#L176-L185).

As I read it, upper.io/db is [fetching values *then* deciding how to convert to the destination](https://github.com/upper/db/blob/c23fa208b136de3d3682db4f6b9293c56fefb421/util/sqlutil/fetch.go#L164). The correct (and more efficient) thing to do is call `Scan` with a slice of `interface{}` that is populated with meaningful destinations. When a particular destination (e.g. struct field) [is a valid Value](http://golang.org/pkg/database/sql/driver/#IsValue), populate the slice with a pointer; the `sql` package will do the conversion. Otherwise (or if you don't want `sql` to convert,) populate the slice with a [`Scanner`](http://golang.org/pkg/database/sql/#Scanner) which is prepared to handle any `Value` and `nil`.

`Scanner` is *the* way to indicate ownership of the conversion process.

**Comment by pkieltyka** [comment]
I agree this is the right approach. I was working on a fork of upper to do exactly that, but got lost in the amount of reflection code required to pull it off.

I took at look at how `sqlx` solved this, and its exactly as you've described: https://github.com/jmoiron/sqlx/blob/master/sqlx.go#L958-L977

thanks @cbandy
