### ISSUE TITLE
Per-session queries support

### ISSUE THREAD

**Issue by davidmz** [lib/pq#384]
For now database/sql and pq don't allow to execute some sql code once per database session. 

For example, if I want change default search_path, I cannot just execute `SET search_path TO my_schema, public;`, because I cannot be sure that my next queries will executed in same database session.

It would be convenient if pq provides a mechanism for automatic execute some sql-queries at the beginning of each session.

**Comment by johto** [comment]
> It would be convenient if pq provides a mechanism for automatic execute some sql-queries at the beginning of each session.

Not really.  This is a feature missing from database/sql.

FWIW I was working on a proposal (see [here](https://go-review.googlesource.com/#/c/2217/)), but the particular API I chose was criticized (though I think that was a mistake).  I'm unlikely to resume this work for Go 1.6, though, so it'd be up to someone else to pick it up.

**Comment by cbandy** [comment]
@johto, is that link correct? iiuc, OP is asking for something like the `options` keyword of libpq.

**Comment by johto** [comment]
I guess I should've paid more attention to the nature of the question, rather than the specifics.

If you just want to change the search_path, you can do that in the connection string:  

```go
sql.Open("postgres", "search_path='foo, public'")
```

libpq arbitrarily divides these into categories, where some options only work if set directly in the connection string (e.g. application_name) and some only work through `options` (e.g. work_mem).  We allow setting everything in the connection string directly.

**Comment by davidmz** [comment]
Thank you very much, @johto! I completely miss this moment in documentation. I really need only search_path, so my problem is solved:)
