### ISSUE TITLE
How to disable prepared statements

### ISSUE THREAD

**Issue by katcipis** [lib/pq#389]
I had some troubles integrating with a pgbouncer that did not had support for prepared statements, I researched a little and found this:

http://stackoverflow.com/questions/17614441/pq-driver-prepared-statement-does-not-exist

Is there a way to disable prepared statements on the driver ?

**Comment by johto** [comment]
> Is there a way to disable prepared statements on the driver ?

pgbouncer should be able to deal with what pq does if the (unfortunately undocumented) option binary_parameters added [here](https://github.com/lib/pq/commit/2997d165a566810a3b9e4d16e7cff1300f744c12) is turned on.  This has, however, some effects on your application; whenever it passes a byte slice as a parameter, it's assumed to be in the binary input format instead of textual.

**Comment by katcipis** [comment]
Thanks @johto

**Comment by rskumar** [comment]
If you turn binary_parameters on, you cannot save JSONB data in PG.

**Comment by jonomacd** [comment]
@rskumar did you ever find a solution for this? We are hoping to use pgbouncer but we also use JSONB.

**Comment by tobischo** [comment]
> If you turn binary_parameters on, you cannot save JSONB data in PG.

Maybe to add to this:
It seems to work if you typecast the `[]byte` slice to `string` before passing it into `Execute`/`Query`/...

e.g.
```go

jsonbData, err = json.Marshal(someStruct)

row := db.QueryRow(
  UpdateQuery,
  id,
  string(jsonbData),
)
```
