### ISSUE TITLE
pq reports error when $PGLOCALEDIR exists

### ISSUE THREAD

**Issue by ymonk** [lib/pq#414]
Found in PostgreSQL versions: 9.4.4 and 9.5rc-1, didn't try for other versions.

Description: when $PGLOCALEDIR is set, pq reports an error indicating $PGLOCALEDIR is not supported and refuse to work. Unset $PGLOCALEDIR make everything work.

Don't know if this is a feature rather than a bug, but since the pg_env.sh script in EnterpriseDB distribution of PostgreSQL sets $PGLOCALEDIR by default, it might make trouble to newbies.

**Comment by johto** [comment]
It's very much intentional that pq works this way.  I believe the idea is that it's very confusing if libpq apps work a certain way but pq apps do something different (namely, use the default values and ignore the environment variables).  The error message looks fine to me, too, so I'm not sure there's really anything to do here.  We have to assume a certain level of competence from our users.  Most "newbies" wouldn't use EnterpriseDB in the first place, either.

**Comment by ymonk** [comment]
Marko, thanks for your explanation. I am fine with it, and will close this issue.
