### ISSUE TITLE
Can't get bound parameters to work with pq.Array

### ISSUE THREAD

**Issue by Dynom** [lib/pq#485]
Hi,

This query returns `f`, this result is unexpected.
```go
	row := db.QueryRow(`
		SELECT EXISTS (
			 SELECT 1
			   FROM information_schema.tables
			  WHERE table_name IN($1)
		)
	`, pq.Array([]string{`table_a`, `table_b`}))

	var result bool
	err := row.Scan(&result)
	if err != nil {
		logger.Log(`method`, `checkForRequiredTables`, `msg`, fmt.Sprintf("%s", err))
	}

	return result
```

This query returns `t`, this result is what I'd expect.
```go
	row := db.QueryRow(`
		SELECT EXISTS (
			 SELECT 1
			   FROM information_schema.tables
			  WHERE table_name IN('table_a', 'table_b')
		)
	`)

	var result bool
	err := row.Scan(&result)
	if err != nil {
		logger.Log(`msg`, fmt.Sprintf("%s", err))
	}

	return result
```

What would be the appropriate way to deal with this?

**Comment by johto** [comment]
```SQL
WHERE table_name = ANY($1)
```

**Comment by Dynom** [comment]
Thanks for your time to write a reply. However I'm unsure why that would solve the inconsistency I encounter. Apparently there is a difference in using 
```
`.. WHERE table_name IN($1)..`, pq.Array([]string{`table_a`, `table_b`})
```

vs

```
`.. WHERE table_name IN('table_a', 'table_b')..`)
```

which I find strange.

**Comment by johto** [comment]
> However I'm unsure why that would solve the inconsistency I encounter.

There isn't any inconsistency here, really.  The argument to an IN is a comma-separated list of values, the same way the argument to a function call is a comma-separated list of values.  For example, this doesn't work:

```SQL
  -- CREATE FUNCTION foof(a int, b int, c int) ...
  SELECT foof($1)
```

because then you'd run into a problem if you had:

```SQL
  -- CREATE FUNCTION foof(arr int[]) ...
  SELECT foof($1)
```

The same principles apply to IN, but for some reason people think about IN differently.  They shouldn't.

**Comment by Dynom** [comment]
I think it would make sense for the library to support these cases as the type supplied as argument doesn't make sense otherwise. Especially since there are more people expecting it to work this way. 

Perhaps because `WHERE .. IN (..)` as a SQL standard, where other versions, like ANY/SOME/ALL are Postgres extensions.

**Comment by johto** [comment]
> I think it would make sense for the library to support these cases as the type supplied as argument doesn't make sense otherwise.

This is problematic, because:

  1. The information that the value was at once point an array is lost by the time it gets to the driver.  You can blame database/sql for that.
  2. Even if it wasn't lost, you should realize that the problem I described in my previous reply still applies.  `pq` would have to parse the query, see that you're doing `WHERE information_schema.tables.table_name IN (...)`, ask the database what the data type of the "table_name" column is, and then change behavior based on that.  Because if "table_name" was an array, IN (<list of arrays>) would make perfect sense, even if that list is only one element in length.

> Especially since there are more people expecting it to work this way.

Tough.  The real world doesn't change just because some people have unreasonable expectations.

**Comment by Dynom** [comment]
Alright, thanks for taking the time to explain the details!
