### ISSUE TITLE
Float type issue

### ISSUE THREAD

**Issue by kuznet1** [lib/pq#522]
```
var val interface{}
err = db.QueryRow("SELECT 36.6::real").Scan(&val)
fmt.Println(val) // "36.599998474121094"

var val2 interface{}
db.QueryRow("SELECT 36.6").Scan(&val2)
fmt.Println(val2) // "[51 54 46 54]"
```
This case is actual when, for example, [rows converting to map](https://gist.github.com/derlin/71b89a3328e6b30e6ef5621a49a4c1a4)

**Comment by cbandy** [comment]
> 1.
```
var val interface{}
err = db.QueryRow("SELECT 36.6::real").Scan(&val)
fmt.Println(val) // "36.599998474121094"
```

At first, I thought this might be due to `extra_float_digits` being [set to `2`](https://github.com/lib/pq/blob/4741650f3c4ff8849f62ccd81879b4cc28d8b969/conn.go#L254) by default, but the backend doesn't emit the value above:

```
$ psql -XAt <<'EOF'
  SET extra_float_digits TO 0; SELECT 36.6::real;
  SET extra_float_digits TO 1; SELECT 36.6::real;
  SET extra_float_digits TO 2; SELECT 36.6::real;
  SET extra_float_digits TO 3; SELECT 36.6::real;
EOF

SET
36.6
SET
36.6
SET
36.599998
SET
36.5999985
```

It's actually [`strconv` that turns any of these](https://play.golang.org/p/aHVceI6b8U) into the number you're seeing. The `float4` parsing has [always been this way](https://github.com/lib/pq/commit/cf316d2848d70cd3898e169ff17217dc16134af2), but I wonder if we should parse the text as 64-bit?

---

> 2.
```
var val2 interface{}
db.QueryRow("SELECT 36.6").Scan(&val2)
fmt.Println(val2) // "[51 54 46 54]"
```

The bare literal `36.6` is interpreted by PostgreSQL as [`numeric`](https://www.postgresql.org/docs/current/static/datatype-numeric.html) type, which has thousands of digits of precision:

```
$ psql -XAtc 'SELECT pg_typeof(36.6)'
numeric
```

We should not try to convert this type to floating-point.

**Comment by kuznet1** [comment]
I think what we should convert postgres types 'real' -> float32 and 'double precision' -> float64, how do you think?

**Comment by kuznet1** [comment]
If this issue is significant, another library can be used. For example, [pqx](github.com/jackc/pgx/stdlib).
