### ISSUE TITLE
StringArray Value method returns nil when slice is nil, I was expecting '{}' instead.

### ISSUE THREAD

**Issue by c4milo** [lib/pq#540]
This was a surprise to me since usually Go's SQL types are not null and there are explicit types to allow inserting null values in the database.  Is this behavior the intended by design or likely a bug?

**Comment by c4milo** [comment]
cc @cbandy

**Comment by cbandy** [comment]
Undefined behavior, I'd say. :wink:

"`nil` when `nil`" sounds intuitive and that's how `encoding/json` behaves. But you're right, our context is `database/sql` and there "`nil` means `NULL`."

Let's come up with the desired behavior, document, and implement it. (or not.) At present,

- `Value` emits `nil`, but `Scan` doesn't accept `nil`. This kind of disparity is usually bad and should probably change.
- Slice types can be `nil`. While `database/sql` users are accustomed to `NullXYZ` types to represent `NULL` values, most types supported by that package cannot be `nil`. The exceptions are `interface{}`, `[]byte`, and `sql.RawBytes`. (I don't recall exactly how `nil` is treated in those cases.)

My starting position is that our types should behave similarly to the exceptions I listed above. Hopefully their behavior is consistent and rational!

**Comment by c4milo** [comment]
@cbandy exactly, I'm in agreement with everything you said :) consistency is key.

**Comment by denyskoch** [comment]
any decisions made?

**Comment by cbandy** [comment]
| type | When scanning `NULL` | When passing `nil` as a parameter |
| --- | --- | --- |
| `interface{}` | assigned `<nil>` | arrives as `NULL` |
| `[]byte` | assigned `[]byte(nil)` | arrives as `''` &sup1; |
| `sql.RawBytes` | assigned `sql.RawBytes(nil)` | not allowed &sup2; |

&sup1; because [`[]byte(nil) != (interface{})(nil)`](https://github.com/lib/pq/blob/d8eeeb8bae8896dd8e1b7e514ab0d396c4f12a1b/conn.go#L1364-L1370). (This makes some sense and to my knowledge, no one has complained about it. Changing how "empty" `[]byte` is handled would likely break apps.)

&sup2; `database/sql` returns an [error in Go 1.7 and earlier](https://travis-ci.org/lib/pq/jobs/178115353#L553-L569): `sql: converting Exec argument #0's type: unsupported type sql.RawBytes, a slice`

So, scanning is rational while passing a parameter is less clear. My impression now is that the array Scan methods should handle `nil`, e.g. `BoolArray.Scan(nil) → BoolArray(nil)`. To be consistent, I think we'd also have to handle something like `GenericArray{ []int(nil) }`.

**Comment by cbandy** [comment]
> My impression now is that the array Scan methods should handle `nil`.

This is contrary to my advice in #490 three months ago.
