### ISSUE TITLE
Float precision error

### ISSUE THREAD

**Issue by hgl** [lib/pq#616]
If I run the following query with pq:

```
var json []byte
err = db.QueryRow(`SELECT json_build_array(121.453556::double precision)`).Scan(&json)
fmt.Println(string(json))
```
I get `[121.45355600000001]`

But if run the same query with `psql`:
```
psql -Aqtc 'SELECT json_build_array(121.453556::double precision)'
```
I get `[121.453556]`

Any idea why the extra digits are added?

**Comment by hgl** [comment]
setting `extra_float_digits` to `0` fixes the problem

**Comment by uhoh-itsmaciek** [comment]
Note that technically setting `extra_float_digits` to 0 *masks* the problem. The full representation of that number does include the `...0001`. It's just that `psql` does not show it by default (`extra_float_digits` is `0`) because it leads to "nicer" display most of the time. `pq` defaults `extra_float_digits` to `2` in order to preserve the actual fidelity of the returned values.

**Comment by hgl** [comment]
Thanks for the detailed explanation.

In my case the numbers are passed to clients as geolocation coordinates. I prefer to send the numbers as they were initially inserted. But now I'll keep the fidelity issue in mind.

Thanks.
