### ISSUE TITLE
Listener.listenerConnLoop infinite retry

### ISSUE THREAD

**Issue by jradtilbrook** [lib/pq#687]
I'm not sure if this is intended or not but it seems like a bug to me; the listenerConnLoop method on Listener will infinitely retry if it cannot connect (eg. connection string is wrong, database is down, etc).

The loop begins [here](https://github.com/lib/pq/blob/master/notify.go#L744).

I think either the documentation is wrong/misleading or this is a bug. The [docs](https://godoc.org/github.com/lib/pq#NewListener) state, somewhat correctly, that the connection will be retried with exponential backoff up until the max. When the max is reached, the timeout is reset and it starts again resulting in an infinite loop.

I'm very new to Go but I suppose the workaround for this is to call panic from the event handler and recover, performing any cleanup or whatever (eg. logging) before exiting? My use case is basically infinitely listening on a Postgres channel and proxying messages to other places but I'd like to check during bootstrap/startup that everything can connect, or at least recover after some time (not indefinite).

Please let me know your thoughts and intended usage

**Comment by johto** [comment]
> I think either the documentation is wrong/misleading or this is a bug. The docs state, somewhat correctly, that the connection will be retried with exponential backoff up until the max.

No, it says that the duration is doubled until the max is reached.  It doesn't say that anything would happen to the connection loop after that.

> When the max is reached, the timeout is reset and it starts again resulting in an infinite loop.

The timeout only reset on successful attempts.

> I'm very new to Go but I suppose the workaround for this is to call panic from the event handler and recover, performing any cleanup or whatever (eg. logging) before exiting? My use case is basically infinitely listening on a Postgres channel and proxying messages to other places but I'd like to check during bootstrap/startup that everything can connect, or at least recover after some time (not indefinite).

I don't think panic would work here, since you'd panic the wrong goroutine.

One way to achieve this would be to open a channel and close that channel from the callback once a connection has been initiated.  Then in the main loop you could select{} with a timeout, and if the timeout is reached before the callback responds through the channel, you simply do your shutdown stuff and exit.  You can call Listener.Close() if you want to, but I'm not sure I'd bother.

**Comment by jradtilbrook** [comment]
Thanks for getting back to me. I still think there is a discrepancy between the documentation and what happens in the connection loop. At the least, it is quite ambiguous which IMO isn't ideal - but I don't want to follow up further.

Thanks for your suggestion. I'll try it out when I get back to the project I was working on!
