### ISSUE TITLE
support for lib/pq sslcompression  question

### ISSUE THREAD

**Issue by nlacey** [lib/pq#861]
I've looked through the code but I'm not seeing any support for sslcompression

https://www.postgresql.org/docs/10/libpq-connect.html

> sslcompression
> 
>     If set to 1 (default), data sent over SSL connections will be compressed. If set to 0, compression will be disabled (this requires OpenSSL 1.0.0 or later). This parameter is ignored if a connection without SSL is made, or if the version of OpenSSL used does not support it.
> 
>     Compression uses CPU time, but can improve throughput if the network is the bottleneck. Disabling compression can improve response time and throughput if CPU performance is the limiting factor.

I was just wondering if you are supporting compression of the ssl stream, and just not allowing it to be turned off?  Or if the sql never gets compressed when connected with ssl?

Thanks for a great product!

**Comment by cbandy** [comment]
No, we don't support compression because Go's TLS implementation does not support compression. To my knowledge, most other TLS implementations also prevent compression.

I was able to find at least one discussion on the mailing list which links to other discussions.

- https://github.com/golang/go/blob/8280455de4728d76f1e084e33284d57eb6ba10ac/src/crypto/tls/common.go#L73-L76
- https://en.wikipedia.org/wiki/Comparison_of_TLS_implementations#Compression
- https://www.postgresql.org/message-id/flat/595cf3b1-4ffe-7f05-6f72-f72b7afa7993%402ndquadrant.com

**Comment by nlacey** [comment]
thanks for the quick response
I appreciate the info.
